// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: VScodeWithSDL

#ifndef _VSCODEWITHSDL_UI_H
#define _VSCODEWITHSDL_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl/lvgl.h"

#include "lv_i18n.h"
#include "ui_helpers.h"
#include "ui_events.h"
void fan_Animation( lv_obj_t *TargetObject, int delay);
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
void ui_event_Screen1( lv_event_t * e);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_Panel1;
extern lv_obj_t *ui_Label1;
extern lv_obj_t *ui_Label2;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
void ui_event_Screen2( lv_event_t * e);
extern lv_obj_t *ui_Screen2;
extern lv_obj_t *ui_Panel2;
extern lv_obj_t *ui_Label3;
extern lv_obj_t *ui_Label4;
extern lv_obj_t *ui_Image2;
extern lv_obj_t *ui_fan;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_974852030);   // assets\fan (6).png
LV_IMG_DECLARE( ui_img_974849980);   // assets\fan (8).png
LV_IMG_DECLARE( ui_img_circle_7_png);   // assets\circle 7.png
LV_IMG_DECLARE( ui_img_circle1_png);   // assets\circle1.png
LV_IMG_DECLARE( ui_img_1595049576);   // assets\hula-hoop1.png
LV_IMG_DECLARE( ui_img_particle_1_png);   // assets\particle_1.png
LV_IMG_DECLARE( ui_img_particle_2_png);   // assets\particle_2.png
LV_IMG_DECLARE( ui_img_particle_3_png);   // assets\particle_3.png
LV_IMG_DECLARE( ui_img_square1_png);   // assets\square1.png
LV_IMG_DECLARE( ui_img_741955754);   // assets\Transmonk-600x275.png
LV_IMG_DECLARE( ui_img_732171207);   // assets\two-arrow1.png
LV_IMG_DECLARE( ui_img_uqoxj1_png);   // assets\uqOXJ1.png
LV_IMG_DECLARE( ui_img_water_1_png);   // assets\water_1.png
LV_IMG_DECLARE( ui_img_water_2_png);   // assets\water_2.png

LV_FONT_DECLARE( ui_font_Big);
LV_FONT_DECLARE( ui_font_Font1);
LV_FONT_DECLARE( ui_font_futur100);
LV_FONT_DECLARE( ui_font_Medium);
LV_FONT_DECLARE( ui_font_mons72);
LV_FONT_DECLARE( ui_font_Number);
LV_FONT_DECLARE( ui_font_Small);
LV_FONT_DECLARE( ui_font_DIGIT);
LV_FONT_DECLARE( ui_font_DIGIT42);
LV_FONT_DECLARE( ui_font_Display16);
LV_FONT_DECLARE( ui_font_Display24);
LV_FONT_DECLARE( ui_font_disp_50);
LV_FONT_DECLARE( ui_font_disp_55);
LV_FONT_DECLARE( ui_font_disp_60);
LV_FONT_DECLARE( ui_font_Font2);
LV_FONT_DECLARE( ui_font_Font24);
LV_FONT_DECLARE( ui_font_Font48);
LV_FONT_DECLARE( ui_font_Font64);
LV_FONT_DECLARE( ui_font_RB10);
LV_FONT_DECLARE( ui_font_RB12);
LV_FONT_DECLARE( ui_font_RB14);
LV_FONT_DECLARE( ui_font_RB16);
LV_FONT_DECLARE( ui_font_RB20);
LV_FONT_DECLARE( ui_font_RB24);
LV_FONT_DECLARE( ui_font_RB26);
LV_FONT_DECLARE( ui_font_RB32);
LV_FONT_DECLARE( ui_font_RB50);
LV_FONT_DECLARE( ui_font_RB60);
LV_FONT_DECLARE( ui_font_RB72);
LV_FONT_DECLARE( ui_font_RB8);
LV_FONT_DECLARE( ui_font_ROBOTO12);
LV_FONT_DECLARE( ui_font_Roboto16);
LV_FONT_DECLARE( ui_font_roboto24);
LV_FONT_DECLARE( ui_font_roboto32);
LV_FONT_DECLARE( ui_font_Roboto40);
LV_FONT_DECLARE( ui_font_Roboto44);
LV_FONT_DECLARE( ui_font_Robotonum72);
LV_FONT_DECLARE( ui_font_RR12);
LV_FONT_DECLARE( ui_font_RR14);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
